language: julia
os:
  - linux
julia:
  - 1.4
notifications:
  email: false
branches:
  only:
    - master
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("ExaPF")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
